Repository ChickenStock-2024/BackEnd, pull requests merged in 2024-08, with the labels that each got.

#49 [#46] Competition API 추가 구현
  .gitignore
  src/main/java/com/sascom/chickenstock/domain/account/repository/AccountRepository.java
  src/main/java/com/sascom/chickenstock/domain/competition/controller/CompetitionController.java
  src/main/java/com/sascom/chickenstock/domain/competition/dto/response/CompetitionHistoryResponse.java
  src/main/java/com/sascom/chickenstock/domain/competition/dto/response/CompetitionListResponse.java
  src/main/java/com/sascom/chickenstock/domain/competition/service/CompetitionService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: Feat

#51 [#33] 시장가 매수, 매도 기능 구현
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/StockOrderRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/util/ChickenStockManager.java
  src/main/resources/data.sql
Labels: Feat

#53 [#50] Rival API 구현
  .gitignore
  src/main/java/com/sascom/chickenstock/domain/rival/controller/RivalController.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/request/RequestEnrollRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/CheckRivalResponse.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseCheckRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseEnrollRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/RivalMemberInfoResponse.java
  src/main/java/com/sascom/chickenstock/domain/rival/entity/Rival.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/RivalExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/code/RivalErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/exception/ExistRivalException.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/exception/NotExistRivalException.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/exception/RivalNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/rival/error/exception/SameMemberException.java
  src/main/java/com/sascom/chickenstock/domain/rival/service/RivalService.java
  src/main/java/com/sascom/chickenstock/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/sascom/chickenstock/global/jwt/JwtResolver.java
  src/main/resources/data.sql
Labels: Feat

#63 [#55] TradeService 구현
  src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/CancelOrderRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/StockOrderRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
  src/main/java/com/sascom/chickenstock/domain/history/error/HistoryExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/history/error/code/HistoryErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/history/error/exception/HistoryNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/socket/MyStompSessionHandler.java
  src/main/java/com/sascom/chickenstock/domain/socket/WebSocketClientConfig.java
  src/main/java/com/sascom/chickenstock/domain/socket/WebSocketClientInitializer.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/ProcessedOrderDto.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/RealStockTradeDto.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/TradeType.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/SellTradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/CancelOrderResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/TradeExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/code/TradeErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/exception/TradeException.java
  src/main/java/com/sascom/chickenstock/domain/trade/service/TradeService.java
  src/main/java/com/sascom/chickenstock/domain/trade/util/ChickenStockManager.java
  src/main/java/com/sascom/chickenstock/domain/trade/util/ChickenStockQueue.java
  src/main/java/com/sascom/chickenstock/domain/trade/util/ChickenStockQueueImpl.java
  src/main/java/com/sascom/chickenstock/domain/trade/util/StockManager.java
  src/main/java/com/sascom/chickenstock/global/entity/BaseTimeEntity.java
  src/main/resources/application.yml
  src/test/java/com/sascom/chickenstock/domain/account/service/AccountServiceTest.java
Labels: Feat

#69 [#68] FcmToken 저장 로직 구현
  src/main/java/com/sascom/chickenstock/domain/fcmtoken/controller/FcmTokenController.java
  src/main/java/com/sascom/chickenstock/domain/fcmtoken/dto/request/FcmTokenRequest.java
  src/main/java/com/sascom/chickenstock/domain/fcmtoken/dto/response/FcmTokenResponse.java
  src/main/java/com/sascom/chickenstock/domain/fcmtoken/entity/FcmToken.java
  src/main/java/com/sascom/chickenstock/domain/fcmtoken/repository/FcmTokenRepository.java
Labels: Feat

#78 [#66] Member Domain 전반적인 리팩토링
  src/main/java/com/sascom/chickenstock/domain/member/controller/MemberController.java
  src/main/java/com/sascom/chickenstock/domain/member/dto/request/ChangeInfoRequest.java
  src/main/java/com/sascom/chickenstock/domain/member/dto/request/ChangePasswordRequest.java
  src/main/java/com/sascom/chickenstock/domain/member/dto/response/ChangeInfoResponse.java
  src/main/java/com/sascom/chickenstock/domain/member/entity/Member.java
  src/main/java/com/sascom/chickenstock/domain/member/error/MemberExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/member/error/code/MemberErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/member/error/exception/MemberImageException.java
  src/main/java/com/sascom/chickenstock/domain/member/error/exception/MemberInfoChangeException.java
  src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
Labels: Refactor

#88 [#79] Login 시에 noti 설정 같이 보내게 수정
  src/main/java/com/sascom/chickenstock/domain/auth/controller/AuthController.java
  src/main/java/com/sascom/chickenstock/domain/auth/dto/response/ResponseLoginMember.java
  src/main/java/com/sascom/chickenstock/domain/auth/service/AuthService.java
  src/main/java/com/sascom/chickenstock/domain/member/dto/MemberInfoForLogin.java
  src/main/java/com/sascom/chickenstock/domain/member/service/MemberFacade.java
  src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
  src/main/java/com/sascom/chickenstock/global/config/AuthenticationManagerConfig.java
  src/main/java/com/sascom/chickenstock/global/config/PasswordEncoderConfig.java
  src/main/java/com/sascom/chickenstock/global/config/WebSecurityConfig.java
  src/main/java/com/sascom/chickenstock/global/oauth/handler/OAuth2SuccessHandler.java
  src/main/resources/application.yml
  src/test/java/com/sascom/chickenstock/domain/auth/AuthControllerTest.java
Labels: Fix

#104 [#76] 과거 주식 데이터 저장 및 갱신 기능 구현
  src/main/java/com/sascom/chickenstock/ChickenstockApplication.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/controller/DailyStockPriceController.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/request/DailyStockPriceRequest.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/request/fis/AccessTokenReqeust.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/response/DailyStockPriceResponse.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/response/kis/AccessTokenResponse.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/response/kis/TodayStock.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/response/kis/TodayStockInfo.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/dto/response/kis/TodayStockPriceResponse.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/entity/DailyStockPrice.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/error/DailyStockPriceExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/error/code/DailyStockPriceErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/error/exception/KisTodayStockPriceException.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/error/exception/KisTokenException.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/repository/DailyStockPriceRepository.java
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/service/DailyStockPriceService.java
  src/main/java/com/sascom/chickenstock/domain/rival/repository/RivalRepository.java
  src/main/resources/application.yml
Labels: Feat

#112 [Hotfix] feat#74 hotfix
  src/main/java/com/sascom/chickenstock/domain/dailystockprice/service/DailyStockPriceService.java
Labels: Fix

#117 [#114] rival api 수정
  src/main/java/com/sascom/chickenstock/domain/rival/controller/RivalController.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/CheckRivalResponse.java
  src/main/java/com/sascom/chickenstock/domain/rival/service/RivalService.java
Labels: Fix
