Repository ChickenStock-2024/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#5 [#1] Rival CRUD 구현
  src/main/java/com/sascom/chickenstock/domain/rival/controller/RivalController.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/request/RequestEnrollRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseCheckRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/dto/response/ResponseEnrollRivalDTO.java
  src/main/java/com/sascom/chickenstock/domain/rival/repository/RivalRepository.java
  src/main/java/com/sascom/chickenstock/domain/rival/service/RivalService.java
Labels: Feat

#16 [#10] Company Read 구현
  src/main/java/com/sascom/chickenstock/domain/company/controller/CompanyController.java
  src/main/java/com/sascom/chickenstock/domain/company/dto/request/CompanyIdRequest.java
  src/main/java/com/sascom/chickenstock/domain/company/dto/response/CompanyInfoResponse.java
  src/main/java/com/sascom/chickenstock/domain/company/entity/Company.java
  src/main/java/com/sascom/chickenstock/domain/company/entity/CompanyStatus.java
  src/main/java/com/sascom/chickenstock/domain/company/error/CompanyExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/company/error/code/CompanyErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/company/error/exception/CompanyNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/company/repository/CompanyRepository.java
  src/main/java/com/sascom/chickenstock/domain/company/service/CompanyService.java
  src/main/java/com/sascom/chickenstock/global/error/BaseExceptionHandler.java
  src/main/java/com/sascom/chickenstock/global/error/GlobalExceptionHandler.java
  src/main/java/com/sascom/chickenstock/global/error/code/GlobalErrorCode.java
  src/main/java/com/sascom/chickenstock/global/error/dto/ErrorResponse.java
  src/test/java/com/sascom/chickenstock/domain/company/repository/CompanyRepositoryTest.java
  src/test/java/com/sascom/chickenstock/domain/company/service/CompanyServiceTest.java
Labels: Feat

#19 [#18] 컴파일 오류 수정
  src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
  src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
  src/main/java/com/sascom/chickenstock/domain/competition/controller/CompetitionController.java
  src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
Labels: Fix

#24 [#20] CompanyLike Create, Delete 구현
  src/main/java/com/sascom/chickenstock/domain/companylike/controller/CompanyLikeController.java
  src/main/java/com/sascom/chickenstock/domain/companylike/dto/response/CompanyLikeResponse.java
  src/main/java/com/sascom/chickenstock/domain/companylike/error/CompanyLikeExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/companylike/error/code/CompanyLikeErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/companylike/error/exception/CompanyLikeNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/companylike/repository/CompanyLikeRepository.java
  src/main/java/com/sascom/chickenstock/domain/companylike/service/CompanyLikeService.java
  src/main/java/com/sascom/chickenstock/domain/member/entity/Member.java
  src/main/java/com/sascom/chickenstock/domain/member/error/MemberExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/member/error/code/MemberErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/member/error/exception/MemberNotFoundException.java
  src/test/java/com/sascom/chickenstock/domain/company/repository/CompanyRepositoryTest.java
  src/test/java/com/sascom/chickenstock/domain/companylike/repository/CompanyLikeRepositoryTest.java
  src/test/java/com/sascom/chickenstock/domain/companylike/service/CompanyLikeServiceTest.java
Labels: Feat

#29 [#23] - 유저의 전체랭킹 조회 기능 구현
  src/main/java/com/sascom/chickenstock/domain/account/entity/Account.java
  src/main/java/com/sascom/chickenstock/domain/member/repository/MemberRepository.java
  src/main/java/com/sascom/chickenstock/domain/member/service/MemberService.java
  src/main/java/com/sascom/chickenstock/domain/ranking/controller/RankingController.java
  src/main/java/com/sascom/chickenstock/domain/ranking/dto/MemberRankingDto.java
  src/main/java/com/sascom/chickenstock/domain/ranking/dto/response/RankingListResponse.java
  src/main/java/com/sascom/chickenstock/domain/ranking/service/RankingService.java
  src/main/java/com/sascom/chickenstock/domain/ranking/util/RatingCalculatorV1.java
Labels: Feat

#30 [#28] 주식 매수, 매도 구현
  src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/BuyStockRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/SellStockRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/error/AccountExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/account/error/code/AccountErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/account/error/exception/AccountNotEnoughException.java
  src/main/java/com/sascom/chickenstock/domain/account/error/exception/AccountNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
  src/main/java/com/sascom/chickenstock/domain/companylike/error/exception/CompanyLikeNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/competition/error/CompetitionExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/competition/error/code/CompetitionErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/competition/error/exception/CompetitionNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/history/entity/History.java
  src/main/java/com/sascom/chickenstock/domain/trade/TradeController.java
  src/main/java/com/sascom/chickenstock/domain/trade/config/TradeConfig.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/TradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/BuyTradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/SellTradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/BuyTradeResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/SellTradeResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/TradeExceptionHandler.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/code/TradeErrorCode.java
  src/main/java/com/sascom/chickenstock/domain/trade/error/exception/TradeNotFoundException.java
  src/main/java/com/sascom/chickenstock/domain/trade/service/TradeService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: Feat

#41 [#32] 매수 매도 로직 DTO 정리
  src/main/java/com/sascom/chickenstock/domain/account/controller/AccountController.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/SellStockRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/dto/request/StockOrderRequest.java
  src/main/java/com/sascom/chickenstock/domain/account/service/AccountService.java
  src/main/java/com/sascom/chickenstock/domain/trade/TradeController.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/TradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/BuyTradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/SellTradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/request/TradeRequest.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/BuyTradeResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/SellTradeResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/dto/response/TradeResponse.java
  src/main/java/com/sascom/chickenstock/domain/trade/service/TradeService.java
Labels: Refactor
